# Generated by Django 5.1.5 on 2025-02-06 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_carriho_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereço',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cep', models.IntegerField(max_length=9)),
                ('Cidade', models.CharField(max_length=60)),
                ('Rua', models.CharField(max_length=60)),
                ('Endereço', models.IntegerField()),
                ('Complemento', models.CharField(max_length=100)),
                ('Referencia', models.TextField()),
                ('Telefone', models.IntegerField(max_length=9)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
