# Generated by Django 5.1.5 on 2025-02-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_endereço'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereço',
            name='Cep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='endereço',
            name='Telefone',
            field=models.IntegerField(),
        ),
    ]
