# Generated by Django 5.1.5 on 2025-02-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='Imagem',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
