# Generated by Django 5.1.5 on 2025-02-02 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse', '0002_alter_produtos_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto_Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cor', models.CharField(max_length=50)),
                ('Preço', models.FloatField()),
                ('Imagem', models.ImageField(upload_to='cores_produto/')),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclipse.produtos')),
            ],
        ),
    ]
