# Generated by Django 5.1.5 on 2025-02-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse', '0003_produto_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto_cor',
            name='Cor_code',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
    ]
