# Generated by Django 5.1.5 on 2025-02-06 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse', '0004_produto_cor_cor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='Categoria',
            field=models.CharField(choices=[('G', 'Gamer'), ('U', 'Upgrade'), ('E', 'Escritorio')], default='E', max_length=3),
        ),
        migrations.CreateModel(
            name='Promoção',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desconto', models.FloatField(default=0)),
                ('Criada', models.DateTimeField(auto_now_add=True)),
                ('Acaba', models.DurationField()),
                ('Estado', models.CharField(choices=[('E', 'Expirado'), ('V', 'Valido')], default={'V', 'Valido'}, max_length=30)),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclipse.produtos')),
            ],
        ),
    ]
